spring:
  config:
    activate:
      on-profile: db-develop

  datasource:
    url: jdbc:mysql://localhost:3306/wsa_mes_library?useSSL=false&characterEncoding=UTF-8&serverTimezone=UTC&autoReconnect=true&failOverReadOnly=false&maxReconnects=10&allowPublicKeyRetrieval=true&createDatabaseIfNotExist=true
    username: root
    password: rlawhdgns4!
    driver-class-name: com.mysql.cj.jdbc.Driver

  # JPA 개발 환경 설정
  jpa:
    defer-datasource-initialization: true
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        show_sql: true
        use_sql_comments: true
        default_batch_fetch_size: 20
        dialect: org.hibernate.dialect.MySQLDialect
    hibernate:
      ddl-auto: update

server:
  port: 8080
  address: 0.0.0.0  # 이 줄 추가

# 개발 환경 로깅
logging:
  level:
    com.example.wsa_mes_library: DEBUG
    org.springframework.web: DEBUG
    org.hibernate.SQL: DEBUG
